/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AskManager {
        /**
          * list of categories of the cookies
         */
        "categories": string[];
        /**
          * last time the privacy policy or which cookies that are used by the website was updated used to know if updated consent is needed can be any string that can be read by Date()
         */
        "cookiePolicyLastUpdated": string;
        "storageName": string;
    }
}
declare global {
    interface HTMLAskManagerElement extends Components.AskManager, HTMLStencilElement {
    }
    var HTMLAskManagerElement: {
        prototype: HTMLAskManagerElement;
        new (): HTMLAskManagerElement;
    };
    interface HTMLElementTagNameMap {
        "ask-manager": HTMLAskManagerElement;
    }
}
declare namespace LocalJSX {
    interface AskManager {
        /**
          * list of categories of the cookies
         */
        "categories"?: string[];
        /**
          * last time the privacy policy or which cookies that are used by the website was updated used to know if updated consent is needed can be any string that can be read by Date()
         */
        "cookiePolicyLastUpdated": string;
        "storageName"?: string;
    }
    interface IntrinsicElements {
        "ask-manager": AskManager;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ask-manager": LocalJSX.AskManager & JSXBase.HTMLAttributes<HTMLAskManagerElement>;
        }
    }
}
